name: autotest
run-name: ${{ github.actor }} made a new push; testing all components.
on: [push, pull_request]
jobs:
  auto-unit-test:
    runs-on: ubuntu-latest
    steps:
      # pulls the repository's code and assigns it to a worker node
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      # executes bash commands to run tests
      - run: cd backend
      - run: npm install
      - run: npm run test